import { createAudioPlayer, setAudioModeAsync, type AudioPlayer } from 'expo-audio';

import { useAccount } from '@/state/AccountProvider';
import { useApp } from '@/state/AppState';

/**
 * Subtle machine sounds (generated by scripts/generate-sounds.js).
 * They respect the phone's silent switch and never stop the user's music.
 */
export type SoundName = 'pull' | 'tick' | 'stop' | 'win';

const SOURCES: Record<SoundName, number> = {
  pull: require('@/assets/sounds/pull.wav'),
  tick: require('@/assets/sounds/tick.wav'),
  stop: require('@/assets/sounds/stop.wav'),
  win: require('@/assets/sounds/win.wav'),
};

const VOLUME: Record<SoundName, number> = { pull: 0.6, tick: 0.25, stop: 0.55, win: 0.5 };

const players: Partial<Record<SoundName, AudioPlayer>> = {};
let audioModeSet = false;

function ensureAudioMode() {
  if (audioModeSet) return;
  audioModeSet = true;
  setAudioModeAsync({ playsInSilentMode: false, interruptionMode: 'mixWithOthers' }).catch(() => {});
}

function playerFor(name: SoundName): AudioPlayer {
  let player = players[name];
  if (!player) {
    player = createAudioPlayer(SOURCES[name]);
    player.volume = VOLUME[name];
    players[name] = player;
  }
  return player;
}

/** Load all sounds up front so the first pull has no delay. */
export function preloadSounds() {
  try {
    ensureAudioMode();
    (Object.keys(SOURCES) as SoundName[]).forEach(playerFor);
  } catch {
    // Sound is a nice-to-have; never crash because of it.
  }
}

export function playSound(name: SoundName) {
  try {
    ensureAudioMode();
    const player = playerFor(name);
    player
      .seekTo(0)
      .then(() => player.play())
      .catch(() => player.play());
  } catch {
    // ignore
  }
}

/** Whether sounds are on (profile setting when signed in, device setting otherwise). */
export function useSoundsEnabled(): boolean {
  const { profile } = useAccount();
  const { state } = useApp();
  return profile?.sounds_enabled ?? state.sounds;
}

/** Plays a sound only if the user has sounds turned on. */
export function useSounds() {
  const enabled = useSoundsEnabled();
  return (name: SoundName) => {
    if (enabled) playSound(name);
  };
}
